import it from './hfs-lang-it.json'
import zh from './hfs-lang-zh.json'
import ru from './hfs-lang-ru.json'
import sr from './hfs-lang-sr.json'
import ko from './hfs-lang-ko.json'
import ms from './hfs-lang-ms.json'
import zh_tw from './hfs-lang-zh-tw.json'
import fr from './hfs-lang-fr.json'
import pt from './hfs-lang-pt.json'
import vi from './hfs-lang-vi.json'
import es from './hfs-lang-es.json'
import nl from './hfs-lang-nl.json'
import el from './hfs-lang-el.json'
import de from './hfs-lang-de.json'
import fi from './hfs-lang-fi.json'

export default { it, zh, ru, sr, ko, ms, 'zh-tw': zh_tw, fr, pt, vi, es, nl, el, de, fi }