import it from './hfs-lang-it.json'
import zh from './hfs-lang-zh.json'
import ru from './hfs-lang-ru.json'
import ro from './hfs-lang-ro.json'
import sr from './hfs-lang-sr.json'
import ko from './hfs-lang-ko.json'
import ms from './hfs-lang-ms.json'
import zh_tw from './hfs-lang-zh-tw.json'
import fr from './hfs-lang-fr.json'
import pt_br from './hfs-lang-pt-br.json'
import vi from './hfs-lang-vi.json'
import es from './hfs-lang-es.json'
import nl from './hfs-lang-nl.json'
import el from './hfs-lang-el.json'
import de from './hfs-lang-de.json'
import fi from './hfs-lang-fi.json'
import hu from './hfs-lang-hu.json'
import ja from './hfs-lang-ja.json'
import tr from './hfs-lang-tr.json'
import th from './hfs-lang-th.json'
import uk from './hfs-lang-uk.json'
import ar from './hfs-lang-ar.json'
import lt from './hfs-lang-lt.json'
import bg from './hfs-lang-bg.json'

export default { it, zh, ru, sr, ko, ms, 'zh-tw': zh_tw, fr, 'pt-br': pt_br, vi, es, nl, el, de, fi, hu, ja, ro, tr, th, uk, ar, lt, bg }