export const SYS_ICONS: Record<string, [string] | [string, string | false]> = { // undefined = font-icon name same as key ; false = no font-icon, only unicode
    login: ['👤','user'],
    user: ['👤','user'],
    filter: ['✂'],
    search: ['🔍'],
    search_off: ['❌','cancel'],
    close: ['❌','cancel'],
    error: ['❌','cancel'],
    stop: ['⏹️'],
    options: ['⚙','cog'],
    archive: ['📦'],
    logout: ['🚪'],
    home: ['🏠'],
    parent: ['⬅','left'],
    folder: ['📂'],
    file: ['📄','doc'],
    spinner: ['🎲','spin6 spinner'],
    password: ['🗝️','key'],
    download: ['⬇️'],
    upload: ['⬆️'],
    reload: ['🔄','reload'],
    lock: ['🔒','lock'],
    admin: ['👑','crown'],
    check: ['✔️'],
    to_start: ['◀'],
    to_end: ['▶'],
    menu: ['☰'],
    list: ['☰','menu'],
    play: ['▶'],
    pause: ['⏸'],
    edit: ['✏️'],
    zoom: ['↔'],
    delete: ['🗑️', 'trash'],
    comment: ['💬'],
    link: ['↗'],
    info: ['ⓘ'],
    cut: ['✄'],
    paste: ['📋'],
    copy: ['⧉'],
    shuffle: ['🔀'],
    repeat: ['🔁', 'reload'],
    success: ['👍', 'check'],
    warning: ['⚠️', false],
    audio: ['🎧'],
    video: ['🎥'],
    image: ['📸'],
    cancel: ['❌','cancel'],
    total: ['➕', 'spin6'],
}
